### ISSUE TITLE
Title and description for pull request should be appropriate.

### ISSUE THREAD

**Issue by vinitshahdeo** [CodeChefVIT/free-slot-finder#5]
The PR title should be concise. The description should exactly explain the changes/updates that will be reflected after the merge.

**Comment by vinitshahdeo** [comment]
@YashMeh @L04DB4L4NC3R 

**Put the PR guidelines in WhatsApp group.**

**Comment by YashMeh** [comment]
How does this looks
ISSUE_TEMPLATE
## Description
As a [USER],
I need [TO DO THIS].

## Mocks
[INSERT RELEVANT PNG FILE]

## Definition of Done
- [ ] All of the required items are completed.

## Estimation of time required
[INSERT NUMBER HERE] hours 

And this for 
PR_TEMPLATE.md
### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [ISSUE]

### Type of Change:
**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality)

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
